all: test.o

test.o: test.c
	gcc -c test.c -o test.o
###

simple::
	./driver.sh alert
	./driver.sh align
	./driver.sh appjs
	./driver.sh ascdesc
	echo ./driver.sh attrMangle
	./driver.sh attrs_escape
	echo ./driver.sh attrs
	./driver.sh autocomp
	./driver.sh bindpat
	./driver.sh DynChannel
	./driver.sh jsonTest
	./driver.sh entities
	./driver.sh fact
	./driver.sh filter
	./driver.sh jsbspace
